### PR TITLE
Tests for list comparison methods were added

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #111

### CODE REVIEW

**Comment by EugeneDar** [comment]
@levBagryansky please, have a look

**Review by levBagryansky — CHANGES_REQUESTED** [review]
@EugeneDar Looks good! But generally speaking, lists can contain objects of different types. I think we need to add tests for lists like below
```
list 
  sscanf
  sprintf
  5
  "Привет"
```

**Comment by EugeneDar** [comment]
@levBagryansky I think this test is not relevant to the current task, because here we are talking about comparing lists, not elements. For this reason the order on the elements must be specified explicitly.
For example, which is more TRUE or FALSE? The list or the number 42? Of course now we can check this by comparing their byte representation, but if we use this approach, any change (e.g. let the byte representation of the bool change) will cause a large number of dropped tests.
But I believe that one is greater than zero and that won't change tomorrow.

**Comment by levBagryansky** [comment]
@EugeneDar I guess it is better to think of how this object must behave in the case above. At least that he does not throw an error or handle it as we want.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
