### PR TITLE
Add `list.withi`

### LINKED ISSUE #116: list.withi
Let's create a new method `.withi` (with, by index), which can replace an element in the list:

```
eq.
  withi.
    list
      * 1 2 3 4 5
    3
    "hello"
  * 1 2 3 "hello" 4 5
```

### PR DESCRIPTION
**Pull request by MikhailLipanin**
closes #116

### CODE REVIEW

**Comment by MikhailLipanin** [comment]
@Graur, can you take a look pls?

**Comment by Graur** [comment]
@MikhailLipanin What would be the behaviour of your implementation if we pass negative index?

**Comment by MikhailLipanin** [comment]
@Graur, since this implementation uses already implemented the `head`, `tail`, `with` and `concat` "methods", these cases are handled.
Additional tests added

**Review by Graur — APPROVED** [review]
@MikhailLipanin Thanks!
@yegor256 Please, heave a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
