### PR TITLE
text.inflated implemented

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: https://github.com/objectionary/eo-collections/issues/99

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Good one, thanks!
@yegor256 Please, take a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
