### PR TITLE
list.inflated returns list object

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #103

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Looks good, thanks!
@yegor256 Please, take a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
