### PR TITLE
map.contains-key implemented

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #119

### CODE REVIEW

**Comment by EugeneDar** [comment]
@c71n93 please have a look

**Review by c71n93 — APPROVED** [review]
@EugeneDar Thanks, looks good for me

**Comment by EugeneDar** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by EugeneDar** [comment]
@yegor256 can you merge again?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
