### PR TITLE
Tests for list.inflated

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: https://github.com/objectionary/eo-collections/issues/94

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Looks good
@yegor256 Can you check if we understand correctly the behaviour of this new `inflated` object, please ?

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
