### PR TITLE
list.contains object

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes: #118
Implemented list.contains

### CODE REVIEW

**Comment by levBagryansky** [comment]
@c71n93 please review

**Review by c71n93 — APPROVED** [review]
@levBagryansky looks good to me

**Comment by levBagryansky** [comment]
@yegor256 please Have a look

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
