### PR TITLE
Redundant parentheses removed

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #104

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Nice refactoring, thanks!
@yegor256 Please, have a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by EugeneDar** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
