### PR TITLE
#139 `list.head` with negative index

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #139 

---

## PR-Codex overview
This PR focuses on improving the implementation of the `head` and `tail` functions in the `list.eo` file. The changes include fixing the handling of negative indices and improving the logic inside the `list.withi` object.

### Detailed summary
- Fixed the `head` function to handle negative indices correctly.
- Improved the logic inside the `list.withi` object to handle negative indices.
- Updated the test cases to reflect the changes.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Good one
@yegor256 Please take a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
