### PR TITLE
Introduced range (#122)

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #122

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur @yegor256 please take a look

**Comment by yegor256** [comment]
@maxonfjvipon it seems that the "de facto" way to generate ranges is `[x, y)`, where `x` is the first element, and `y` is the last element that _is not inside_ the range. Thus, as a user of `range` I would expect this (the `4` is not inside the range):

```
eq.
  range
    1
    [i] i.plus 1 > @
    4
  * 1 2 3
```

I may be wrong, though. Let's check how other languages do this.

**Comment by maxonfjvipon** [comment]
@yegor256 it's from official [php docs](https://www.php.net/manual/en/function.range.php):
```

<?php
// array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
foreach (range(0, 12) as $number) {
    echo $number;
}

```

But python range works differently:

image

So I think we just have to decide how it should work in eo. There is no any standard or rule

**Comment by yegor256** [comment]
@maxonfjvipon I like the Python's way

**Comment by maxonfjvipon** [comment]
@yegor256 OK

**Comment by maxonfjvipon** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
