### PR TITLE
Update EO version to 0.29.4

### LINKED ISSUE #171: Upgrade EO version to `0.29.4`

### PR DESCRIPTION
**Pull request by mximp**
closes #171

---

## PR-Codex overview
This PR updates the version of `eo-runtime` and `eo-maven-plugin`. It also corrects a typo in the `README.md` file. 

### Detailed summary:
- Updated `eo-runtime` version from `0.29.2` to `0.29.4`
- Updated `eo-maven-plugin` version from `0.29.2` to `0.29.4`
- Corrected a typo in the `README.md` file

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@mximp mvn fails in GHA :(

**Comment by mximp** [comment]
/codex How would I thoroughly test this change?

**Comment by mximp** [comment]
The update has been done in another PR #173

**Pull request closed without merging**
