### PR TITLE
24 removed map

### PR DESCRIPTION
**Pull request by levBagryansky**
@Graur please review
I removed deprecated `map`  according to #24

### CODE REVIEW

**Comment by Graur** [comment]
@levBagryansky Please, restart github actions checks

**Comment by Graur** [comment]
@levBagryansky Please, restart github actions checks

**Comment by levBagryansky** [comment]
@Graur done

**Review by Graur — APPROVED** [review]
@levBagryansky Good one!

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@levBagryansky Thanks!

**Pull request merged**
