### PR TITLE
28 rewrite

### PR DESCRIPTION
**Pull request by levBagryansky**
@Graur , please review.
I rewrited `with` attribute for `list` according to #28

### CODE REVIEW

**Comment by Graur** [comment]
@levBagryansky But `list` already have this object, since it decorates `array`

**Comment by levBagryansky** [comment]
> @levBagryansky But `list` already have this object, since it decorates `array`

Yes, but `with` returtns `array` instead of `list`. So the test 
```
[] > concat-of-two-lists
  list (* 1 2) > list1
  without. > list2
    with.
      list1
      3
    0
  assert-that > @
    list2.at 0
    $.equal-to 2
```
will fail wthout rewrited `with` will fail.

**Review by Graur — APPROVED** [review]
@yegor256 please, have a look

**Review by Graur — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 , look please

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
